name: CI Testing
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  lint-pw-lesson-30: 
    name: 'Lint PW folder lesson 30'
    runs-on: ubuntu-latest
    container:
     image: node:22-slim
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        working-directory: ./lesson-30
        run: npm ci
      - name: Run lint
        working-directory: ./lesson-30
        run: npm run lint
  typecheck-pw-lesson-30: 
    name: 'Typecheck PW folder lesson 30'
    needs: lint-pw-lesson-30
    runs-on: ubuntu-latest
    container:
     image: node:22-slim
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        working-directory: ./lesson-30
        run: npm ci
      - name: Run typecheck
        working-directory: ./lesson-30
        run: npm run build
  tests-pw-default-image: 
    name: 'PW e2e tests on default image'
    needs: typecheck-pw-lesson-30
    runs-on: ubuntu-latest
    container:
     image: mcr.microsoft.com/playwright:v1.54.2-noble
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        working-directory: ./lesson-30
        run: npm ci
      - name: Run e2e tests
        working-directory: ./lesson-30
        env:
          TESTOMATIO: ${{ secrets.TESTOMATIO }}
          TESTOMATIO_CREATE: ${{ vars.TESTOMATIO_CREATE }}
        run: |
              npm run pw:test:ci:chromium:all-non-setup
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-default
          path: |
                lesson-30/playwright-report/
                lesson-30/test-results/
                lesson-30/results.xml
          retention-days: 30
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'lesson-30/results.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
  tests-pw-custom-image: 
    name: 'PW e2e tests on custom image'
    needs: tests-pw-default-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: 
          node-version: lts/*
      - name: Install playwright
        run: npx -y playwright@1.54.2 install --with-deps
      - name: Install dependencies
        working-directory: ./lesson-30
        run: npm ci
      - name: Run e2e tests
        working-directory: ./lesson-30
        env:
          TESTOMATIO: ${{ vars.TESTOMATIO }}
          TESTOMATIO_CREATE: ${{ vars.TESTOMATIO_CREATE }}
        run: |
              npm run pw:test:ci:chromium:setup
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-custom
          path: |
                lesson-30/playwright-report/
                lesson-30/test-results/
                lesson-30/results.xml
          retention-days: 30
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'lesson-30/results.xml'
          token: ${{ secrets.GITHUB_TOKEN }}