name: CI Testing
on:
  push:
    branches:
      - "*"
  pull_request:
    types: ['opened']
jobs:
  tests-pw-default-image: 
    name: 'PW e2e tests on default image'
    runs-on: ubuntu-latest
    container:
     image: mcr.microsoft.com/playwright:v1.54.0
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./lesson-26
        run: npm ci
      - name: Run e2e tests
        working-directory: ./lesson-26
        run: |
              npm run pw:test:chromimum
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-default
          path: |
                lesson-26/playwright-report/
                lesson-26/test-results/
                lesson-26/results.xml
          retention-days: 30
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'lesson-26/results.xml'
          token: ${{ env.JUNITKEY }}